export const ARTISTS = [

    // =========================
    // GLOBAL / TOP NIGERIAN STARS
    // =========================
  
    'Burna Boy',
    'Wizkid',
    'Davido',
    'Rema',
    'Tems',
    'Asake',
    'Ayra Starr',
    'Olamide',
    'Tiwa Savage',
    'Fireboy DML',
    'Omah Lay',
    'Kizz Daniel',
    'BNXN',
    'Seyi Vibez',
    'Yemi Alade',
    'Flavour',
    '2Baba',
    'D\'banj',
    'P-Square',
    'Patoranking',
    'Tekno',
    'Mr Eazi',
    'Korede Bello',
    'Phyno',
    'Chike',
    'Runtown',
    'Kcee',
    'Timaya',
    'Wande Coal',
    'Naira Marley',
    'Zlatan',
    'Ruger',
    'Joeboy',
    'Ckay',
    'Victony',
    'Lojay',
    'Fave',
    'Bella Shmurda',
    'Zinoleesky',
    'Shallipopi',
    'Odumodublvck',
    'Blaqbonez',
    'Ladipoe',
    'Falz',
    'Ycee',
    'Lil Kesh',
    '9ice',
    'Skales',
  
    // =========================
    // ESTABLISHED / MAINSTREAM
    // =========================
  
    'Simi',
    'Adekunle Gold',
    'Johnny Drille',
    'Teni',
    'Niniola',
    'Waje',
    'Chidinma',
    'Praiz',
    'Oxlade',
    'Mayorkun',
    'Peruzzi',
    'May D',
    'Dremo',
    'Yung6ix',
    'Dice Ailes',
    'Reekado Banks',
    'Di\'Ja',
    'Iyanya',
    'Dammy Krane',
    'Pheelz',
    'Maleek Berry',
    'Sarz',
    'Show Dem Camp',
    'M.I Abaga',
    'A-Q',
    'Vector',
    'Reminisce',
    'Jesse Jagz',
    'Illbliss',
    'Ice Prince',
    'Naeto C',
    'Mode 9',
    'Eedris Abdulkareem',
    'Ruggedman',
    'D\'Prince',
    'Banky W',
    'Lynxxx',
    'Dr SID',
    'Don Jazzy',
    'Moelogo',
    'Harrysong',
    'Solidstar',
    'Jaywon',
    'Oritsefemi',
    'YQ',
    'J Martins',
    'Bracket',
    'Duncan Mighty',
    'Sound Sultan',
    'Brymo',
    'Bez',
    'Waconzy',
    'Tony Tetuila',
    'Olu Maintain',
    'Jazzman Olofin',
    '2Shotz',
    'Bigiano',
    'Konga',
    'Zule Zoo',
    'Styl-Plus',
    'Kas',
    'Tosin Martins',
    'Weird MC',
    'Sasha P',
    'TY Bello',
    'Zaki Adze',
    'Bouqui',
    'Dipp',
  
    // =========================
    // STREET / AFROBEATS / POP
    // =========================
  
    'Mohbad',
    'Portable',
    'TML Vibez',
    'Muyeez',
    'Famous Pluto',
    'Fido',
    'Ayo Maff',
    'BoyPee',
    'Brown Joel',
    'Hyce',
    'Kashcoming',
    'Barry Jhay',
    'Qdot',
    'Small Doctor',
    'Otega',
    'C Blvck',
    'Abuga',
    'Crayon',
    'Magixx',
    'Boy Spyce',
    'L.A.X',
    'Young Jonn',
    'Poco Lee',
    'Lil Frosh',
    'Lyta',
    'Oladips',
    'Terry G',
    'Danny Young',
    'Slimcase',
    'Mr Real',
    'Idowest',
    '1da Banton',
    'Terri',
    'Dice Ailes',
  
    // =========================
    // NEW SCHOOL / RISING
    // =========================
  
    'FOLA',
    'Mavo',
    'Kunmie',
    'Llona',
    'Qing Madi',
    'Morravey',
    'Taves',
    'Kaestyle',
    'Jiggy Boyz',
    'Elinala',
    '6unny',
    'Juno',
    'Champz',
    'Priesst',
    'Danpapa GTA',
    'ZerryDL',
    'Zaylevelten',
    'Kidd Carder',
    'OML',
    '6uff',
    'KVNBLAQ',
    'Faceless',
    'Serotonin',
    'Smur Lee',
    'El Jack',
    'Shoday',
    'Boy Muller',
    'Khaid',
    'Guchi',
    'Bayanni',
    'Lifesize Teddy',
    'Rexxie',
    'Chella',
    'Black Astro',
    'Ellacentric',
    'Yamayeh Vibez',
    'Mayowa Afolabi',
    'Dellfire',
    'Blinkz Baba',
    'El Nayaan',
    'Solana',
    'Dre Foryoursoul',
    'ELMAH',
    'Dxtiny',
    'Tension',
    'Patomant',
    'NO11',
    'Ayjay Bobo',
    'Monochrome',
    'Kurry',
    'Mckay',
    'Kxyyz',
    'Oxygenmix',
    'Kayroz',
    'Kayyzzz',
    'Tayo Creed',
    'BoiGizmo',
    'Ṣẹwà',
    'Serøtonin',
    'MYRON',
    'Miiles44',
    'Strei',
    'Celo',
    'Kemuel',
    'JahRay D\'Hov',
    'TSO',
  
    // =========================
    // ALTÉ / R&B / ALTERNATIVE
    // =========================
  
    'Tay Iwar',
    'Nonso Amadi',
    'Wurld',
    'Odunsi (The Engine)',
    'Cruel Santino',
    'Prettyboy D-O',
    'Tomilola',
    'Lady Donli',
    'Asa',
    'Tomi Thomas',
    'BOJ',
    'Ajebutter22',
    'Santi',
    'WANI',
    'Nissi',
    'GoodGirl LA',
    'Tomi Agape',
    'Dami Oniru',
    'SGaWD',
    'Somadina',
    'Maka',
    'Teezee',
    'Maison2500',
    'PsychoYP',
    'Tjan',
  
    // =========================
    // FEMALE NIGERIAN ARTISTS
    // =========================
  
    'Seyi Shay',
    'Niyola',
    'Aramide',
    'Yinka Davies',
    'Cynthia Morgan',
    'Mo\'Cheddah',
    'Eva Alordiah',
    'Bloody Civilian',
    'Bella Alubo',
    'Lami Phillips',
    'Lindsey Abudei',
    'Tomi Owo',
    'Nneka',
    'Ego',
  
    // =========================
    // HIP-HOP / RAP
    // =========================
  
    'Erigga',
    'Sinzu',
    'Dandizzy',
    'Alpha Ojini',
    'Paybac',
    'Boogey',
    'Teeto Ceemos',
    'Trybesmen',
    'Dagrin',
    'Terry Tha Rapman',
    'Pherosh',
    'Baron',
    'Yung L',
    'Endia',
    'Vtek',
  
    // =========================
    // GOSPEL / CHRISTIAN
    // =========================
  
    'Sinach',
    'Mercy Chinwo',
    'Nathaniel Bassey',
    'Joe Praize',
    'Frank Edwards',
    'Tope Alabi',
    'Dunsin Oyekan',
    'Moses Bliss',
    'Judikay',
    'Victoria Orenze',
    'Minister GUC',
    'Samsong',
    'Onos Ariyo',
    'Ada Ehi',
    'Tim Godfrey',
    'Lawrence Oyor',
    'Sunmisola Agbebi',
    'Theophilus Sunday',
    'Ebuka Songs',
    'Esther Igbekele',
    'Preye Odede',
    'Steve Crown',
    'Chris Morgan',
    'Jimmy D Psalmist',
    'Greatman Takit',
    'Nosa',
    'Sammie Okposo',
    'Kefee',
    'Mike Abdul',
    'Monique',
    'Glowreeyah Braimah',
    'Kaestrings',
    'Gabriel Eziashi',
    'Chingtok Ishaku',
    'Bidemi Olaoba',
    'Tosin Bee',
    'Mr M & Revelation',
  
    // =========================
    // HIGHLIFE / JUJU / FUJI / LEGENDS
    // =========================
  
    'Fela Kuti',
    'Femi Kuti',
    'Seun Kuti',
    'Tony Allen',
    'Lagbaja',
    'King Sunny Ade',
    'Ebenezer Obey',
    'I.K. Dairo',
    'Osita Osadebe',
    'Oliver De Coque',
    'Rex Lawson',
    'Victor Uwaifo',
    'Sir Shina Peters',
    'Sunny Neji',
    'Majek Fashek',
    'Bobby Benson',
    'Orlando Julius',
    'William Onyeabor',
    'Onyeka Onwenu',
    'Christy Essien Igbokwe',
    'Sade Adu',
    'Evi Edna Ogholi',
    'Salawa Abeni',
    'Ras Kimono',
    'Daniel Wilson',
    'Felix Liberty',
    'Bongos Ikwue',
    'Jide Obi',
    'Alex O',
    'Mike Okri',
    'Kenny Ogungbe',
    'Bright Chimezie',
    'Sunny Okosun',
    'Inyang Henshaw',
    'Dan Maraya Jos',
    'Mamman Shata',
    'Haruna Ishola',
    'Ayinla Omowura',
    'Sikiru Ayinde Barrister',
    'Kollington Ayinla',
    'Wasiu Ayinde Marshall',
    'Abass Akande Obesere',
    'Saheed Osupa',
    'Pasuma',
    'Adewale Ayuba',
    'Yinka Ayefele',
  
    // =========================
    // PRODUCERS / DJs (NIGERIAN)
    // =========================
  
    'Legendury Beatz',
    'Masterkraft',
    'DJ Spinall',
    'DJ Neptune',
    'DJ Kaywise',
    'DJ Tunez',
    'DJ Big N',
    'DJ Consequence',
    'DJ Lambo',
    'DJ Jimmy Jatt',
    'DJ Xclusive',
    'DJ Prince',
    'Kel-P',
    'Killertunes',
    'Blaise Beatz',
    'Niphkeys',
    'London',
    'P.Priime',
    'Type A',
    'Telz',
    'Magicsticks',
    'Amapiano Disciple',
    'Sunnex',
    'Shizzi',
    'Speroach Beatz',
    'Chopstix'
  ];